base_url = "https://venicteam.github.io"
title = "Voice Enabled Intelligent Programming Assistant"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
logo = "https://venicteam.github.io/logo.png"
release = "https://api.github.com/repos/venicteam/core/releases/latest"
favicon = "https://venicteam.github.io/logo.png"
